### ISSUE TITLE
hiding proofs does not work with Coq 8.5

### ISSUE THREAD

**Issue by benediktahrens** [gverdier/coqdoc-overlay#1]
It seems that the coqdoc output has changed between 8.4 and to-be 8.5, so that the proof toggling does not work in 8.5 anymore.
Any chance you can fix this? We are using that feature in https://github.com/UniMath/UniMath.

**Comment by gverdier** [comment]
This should be fixed by commit 821227442305a44eb52f122572a18a6c6311100b.
